Do the hpack verification in temporary directory

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -52,17 +52,19 @@ jobs:
 
     - name: Check that .cabal file has not changed except hpack comment
       run: |
-        CABAL_FILE="jbeam-edit.cabal"
-        git show HEAD:$CABAL_FILE > committed.cabal
-        cp $CABAL_FILE current.cabal
-        tail -n +2 committed.cabal > committed_trimmed.cabal
-        tail -n +2 current.cabal > current_trimmed.cabal
-        if ! diff -q committed_trimmed.cabal current_trimmed.cabal > /dev/null; then
-          echo "Error: .cabal file has changed beyond the expected hpack comment line."
-          echo "Please commit the updated .cabal file if this is intentional."
-          exit 1
+        CABAL_FILE=jbeam-edit.cabal
+        TMP_DIR=$(mktemp -d)
+        git show HEAD:$CABAL_FILE > $TMP_DIR/committed.cabal
+        cp $CABAL_FILE $TMP_DIR/current.cabal
+        tail -n +2 $TMP_DIR/committed.cabal > $TMP_DIR/committed_trimmed.cabal
+        tail -n +2 $TMP_DIR/current.cabal > $TMP_DIR/current_trimmed.cabal
+
+        if ! diff -q $TMP_DIR/committed_trimmed.cabal $TMP_DIR/current_trimmed.cabal > /dev/null; then
+        echo "Error: .cabal file has changed beyond the expected hpack comment line."
+        echo "Please commit the updated .cabal file if this is intentional."
+        exit 1
         else
-          echo ".cabal file is unchanged except for the first comment line."
+        echo ".cabal file is unchanged except for the first comment line."
         fi
 
     - name: Run tests
